#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Mar 01, 2023 10:24:10 AM +03  platform: Windows NT

import tkinter as tk

import new_project_window

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = new_project_window.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    new_project_window.start_up()




